"""
Self-Channel k Nearest Neighbors and Distance Analysis
========================================================
Mirror of the cross-channel distance processing, adapted for
same-channel (self) nearest-neighbor distances.

Assumes the same upstream pipeline:
    output  = drop.condensate(...)
    _, _, distance_dict_list, _, _ = dNN.distanceNN(output, zHeight, False, False)
    self_distance_list, _, objs    = dNN.self_distNN(output, zHeight, False, False)

OBJECT ATTRIBUTE:
  Both cross-channel and self-channel NN are stored in:
      obj.characteristics['dist'][target_ch] -> (distance, target_obj)
  For self-channel, target_ch == obj.channel.

Code was generated by Claude and "the relevant parts were" verified by STP
"""

import numpy as np
import matplotlib.pyplot as plt
import droplet10Jul25_smooth as drop
import distNN20Apr25 as dNN
import pandas as pd
import os

# ============================================================
# 0) Upstream pipeline (same as cross-channel script)
# ============================================================

supdirectory = r'ND6 data'
folders = os.listdir(supdirectory)
sddict_list = []
obl = []
for folder in folders:
    directory = supdirectory + '/' + folder
    zHeight = 0.130
    
    print(folder)
    match int(folder):
        case 1:
            intens = [200, 450, 300]
            zsl = [6, 16]
            pmu = 0.035
        case 2:
            intens = [180, 400, 350]
            zsl = [6, 20]
            pmu = 0.065
        case 3:
            intens = [150, 450, 400]
            zsl = [5, 20]
            pmu = 0.065
        case 4:
            intens = [180, 350, 280]
            zsl = [6, 17]
            pmu = 0.065
        case 5:
            intens = [200, 450, 400]
            zsl = [7, 19]
            pmu = 0.065
        case 6:
            intens = [180, 400, 380]
            zsl = [2, 18]
            pmu = 0.065
        case 7:
            intens = [180, 380, 360]
            zsl = [7, 17]
            pmu = 0.065
        case 8:
            intens = [180, 380, 360]
            zsl = [6, 21]
            pmu = 0.065
    
    output = drop.condensate(directory,
                             pmu,
                             intensities=intens,
                             timesteps=[1],
                             zstacks=zsl,
                             channels=[1, 3, 4],
                             windowsizes=[5],
                             masksizes=[4],
                             backints='Calculated',
                             smooth=False,
                             sigma=1.0,
                             plot = 'Suppress'
                             )
    
    _, _, distance_dict_list, _, _ = dNN.distanceNN(output, zHeight, False, False)
    self_distance_list, _, objs = dNN.self_distNN(output, zHeight, False, False)

    sddict_list.append(self_distance_list[0])
    obl.append(objs[0])
# ============================================================
# Build self_distance_dict  (channel -> [distances])
# ============================================================

self_distance_dict = {}
for sd in sddict_list:
    for key in sd.keys():
        if key in self_distance_dict:
            self_distance_dict[key] += sd[key]
        else:
            self_distance_dict[key] = sd[key]

# Unpadded copy for trimming later
self_distance_dict_raw = {k: list(v) for k, v in self_distance_dict.items()}

# Flatten all puncta from objs
all_puncta = []
for sublist in obl:
    all_puncta += sublist

# ============================================================
# A) FULL self-distance CSV  (wide format)
#    -> SelfChannel_3ChannelImages.csv
# ============================================================

temp = [len(self_distance_dict[key]) for key in self_distance_dict.keys()]
max_len = max(temp)

self_distance_dict_padded = {}
for key in self_distance_dict.keys():
    self_distance_dict_padded[f'self_{key}'] = (
        list(self_distance_dict[key]) + [None] * (max_len - len(self_distance_dict[key]))
    )

df_full_self = pd.DataFrame(self_distance_dict_padded)
df_full_self.to_csv('SelfChannel_3ChannelImages.csv', index=False)
print("Saved full self-channel distances to SelfChannel_3ChannelImages.csv")

# ============================================================
# B) TRIMMED self-distances <= 5 µm  (wide format)
#    -> SelfChannel_3ChannelImages_upto5um.csv
# ============================================================

self_distance_dict_trim = {}
for key, vals in self_distance_dict_raw.items():
    trimmed_vals = [d for d in vals if d <= 5]
    self_distance_dict_trim[f'self_{key}'] = trimmed_vals

temp_trim = [len(v) for v in self_distance_dict_trim.values()]
max_trim = max(temp_trim) if temp_trim else 0

for key in self_distance_dict_trim.keys():
    self_distance_dict_trim[key] = (
        list(self_distance_dict_trim[key]) + [None] * (max_trim - len(self_distance_dict_trim[key]))
    )

df_trim_self = pd.DataFrame(self_distance_dict_trim)
df_trim_self.to_csv('SelfChannel_3ChannelImages_upto5um.csv', index=False)
print("Saved self-channel distances <= 5 um to SelfChannel_3ChannelImages_upto5um.csv")

# ============================================================
# C) LONG-FORMAT: all self-channel NN pairs with d <= 5 µm
#    Keep distance + source/target intensities and sizes
#    -> selfDistNN_upto5um_long.csv
#
#    Self-channel NN is stored in:
#       obj.characteristics['dist'][obj.channel] -> (distance_um, target_obj)
# ============================================================

rows_self_trimmed = []

for src in all_puncta:
    src_ch = src.channel

    # Check that the object has a self-channel NN recorded
    if 'dist' not in src.characteristics:
        continue
    if src_ch not in src.characteristics['dist']:
        continue

    dist_um, tgt_obj = src.characteristics['dist'][src_ch]

    if dist_um <= 5:
        rows_self_trimmed.append({
            'pair': f'{src_ch} vs {src_ch}',
            'channel': src_ch,
            'distance_um': dist_um,
            'source_intensity': src.punctumIntensity,
            'target_intensity': tgt_obj.punctumIntensity,
            'source_size_um': src.majorSize,
            'target_size_um': tgt_obj.majorSize,
        })

df_self_long = pd.DataFrame(rows_self_trimmed)
df_self_long.to_csv('selfDistNN_upto5um_long.csv', index=False)

print("Saved long-format self-channel d<=5um NN table to selfDistNN_upto5um_long.csv")
print("Pairs included:", df_self_long['pair'].unique() if len(df_self_long) else 'none')
print("Total self-channel NN pairs (d<=5um):", len(df_self_long))

# ============================================================
# D) Wide-format self-distance tables with intensity filtering
#    For channel 1: split into >=1000 and <1000 source intensity
#    Channels 3, 4: all d<=5 um entries
#    -> SelfChannel_upto5um_HighInt_ch1.csv
#    -> SelfChannel_upto5um_LowInt_ch1.csv
# ============================================================

self_pairs = ['1 vs 1', '3 vs 3', '4 vs 4']


def build_self_wide_table(df_long, pairs, mode='high'):
    """
    mode = 'high' -> channel 1 self-NN with source_intensity >= 1000
    mode = 'low'  -> channel 1 self-NN with source_intensity < 1000
    Channels 3, 4: all d<=5 um entries (unchanged)
    """
    data = {}

    for p in pairs:
        df_pair = df_long[df_long['pair'] == p]

        if p == '1 vs 1':
            if mode == 'high':
                df_sel = df_pair[df_pair['source_intensity'] >= 1000]
            else:
                df_sel = df_pair[df_pair['source_intensity'] < 1000]
        else:
            df_sel = df_pair

        data[p] = df_sel['distance_um'].tolist()

    # Pad to equal length
    max_len = max(len(v) for v in data.values()) if data else 0
    for k in data:
        if len(data[k]) < max_len:
            data[k] = data[k] + [None] * (max_len - len(data[k]))

    return pd.DataFrame(data)


if len(df_self_long) > 0:
    # HIGH-intensity version
    df_self_high = build_self_wide_table(df_self_long, self_pairs, mode='high')
    df_self_high.to_csv('SelfChannel_upto5um_HighInt_ch1.csv', index=False)
    print("Saved SelfChannel_upto5um_HighInt_ch1.csv")
    print("Counts per self-pair (high):")
    print(df_self_high.count())

    # LOW-intensity version
    df_self_low = build_self_wide_table(df_self_long, self_pairs, mode='low')
    df_self_low.to_csv('SelfChannel_upto5um_LowInt_ch1.csv', index=False)
    print("Saved SelfChannel_upto5um_LowInt_ch1.csv")
    print("Counts per self-pair (low):")
    print(df_self_low.count())
else:
    print("No self-channel NN pairs found within 5 um — skipping intensity-split tables.")

# ============================================================
# E) Log-histogram plots of self-channel NN distances
#    (same as original but for self-channel)
# ============================================================


def plot_loghist(x, bins, plot):
    hist, bins = np.histogram(x, bins=bins, range=(0.001, 10))
    logbins = np.logspace(np.log10(bins[0]), np.log10(bins[-1]), len(bins))
    n, hist2, bins2 = plot.hist(x, bins=logbins, alpha=0.5)
    plot.set_xscale('log')
    return n, logbins


channel_labels = {
    1: 'mtRNA Channel',
    3: 'mtRNA Granule Channel',
    4: 'mtDNA Channel',
}

for ch in self_distance_dict_raw.keys():
    fig, ax = plt.subplots()

    label = channel_labels.get(ch, f'Channel {ch}')
    fig.suptitle(f'Self-Channel NN Distances: {label}')

    plot_loghist(self_distance_dict_raw[ch], 35, ax)
    ax.set_xlabel('Distance Log Microns')
    ax.set_ylabel('Count')
    ax.set_ylim((0, 1200))

    filename_base = f"SelfNN_{label.replace(' ', '_')}"
    fig.savefig(f"{filename_base}.pdf", format='pdf')
    fig.savefig(f"{filename_base}.eps", format='eps')
    plt.show()

# ============================================================
# F) Self-channel distance vs source intensity scatter plots
#    One per channel, d <= 5 µm, split by intensity threshold
# ============================================================

# Separate puncta by channel
l1 = [obj for obj in all_puncta if obj.channel == 1]
l3 = [obj for obj in all_puncta if obj.channel == 3]
l4 = [obj for obj in all_puncta if obj.channel == 4]

# Intensity thresholds per channel (mirrors cross-channel thresholds)
intensity_thresholds = {1: 1000, 3: 5000, 4: 4000}


def extract_self_dist(puncta_list):
    """Extract self-channel NN distance and target object from each punctum."""
    records = []
    for p in puncta_list:
        if 'dist' not in p.characteristics:
            continue
        if p.channel not in p.characteristics['dist']:
            continue

        d, tgt = p.characteristics['dist'][p.channel]

        records.append({
            'distance_um': d,
            'source_intensity': p.punctumIntensity,
            'source_size_um': p.majorSize,
            'target_intensity': tgt.punctumIntensity,
            'target_size_um': tgt.majorSize,
        })
    return pd.DataFrame(records)


for ch, ch_puncta, ch_label in [
    (1, l1, 'mtRNA'),
    (3, l3, 'mtRNA_Granule'),
    (4, l4, 'mtDNA'),
]:
    df_ch = extract_self_dist(ch_puncta)
    if df_ch.empty:
        print(f"Channel {ch}: no self-channel NN data found — skipping.")
        continue

    # Flag distance <= 5 um
    df_ch['within_5um'] = df_ch['distance_um'] <= 5

    thresh = intensity_thresholds[ch]
    df_ch['I_class'] = np.where(
        df_ch['source_intensity'] >= thresh,
        f'>={thresh}',
        f'<{thresh}',
    )

    # Save per-channel CSV
    csv_name = f'SelfNN_ch{ch}_distance_vs_intensity.csv'
    df_ch.to_csv(csv_name, index=False)
    print(f"Saved {csv_name}")

    # Subset to d <= 5 um
    df_5 = df_ch[df_ch['within_5um']]
    low_mask = df_5['source_intensity'] < thresh
    high_mask = df_5['source_intensity'] >= thresh

    # ---- Plot: I < threshold ----
    plt.figure()
    plt.scatter(
        df_5.loc[low_mask, 'distance_um'],
        df_5.loc[low_mask, 'source_intensity'],
        s=14, color='#1f77b4',
    )
    plt.xlabel(f'Self-channel {ch} NN distance (µm)')
    plt.ylabel(f'Channel {ch} intensity (a.u.)')
    plt.title(f'Self {ch} vs {ch}: d ≤ 5 µm — intensity < {thresh}')
    plt.xlim(0, 5)
    plt.ylim(0, max(6000, thresh * 2))
    n_low = low_mask.sum()
    plt.text(
        0.05, 0.95, f'n(<{thresh}) = {n_low}',
        transform=plt.gca().transAxes, fontsize=10, va='top',
        bbox=dict(facecolor='white', alpha=0.7, edgecolor='none'),
    )
    plt.savefig(f'SelfNN_ch{ch}_int_lt{thresh}_dle5um.pdf', format='pdf')
    plt.savefig(f'SelfNN_ch{ch}_int_lt{thresh}_dle5um.eps', format='eps')
    plt.show()

    # ---- Plot: I >= threshold ----
    plt.figure()
    plt.scatter(
        df_5.loc[high_mask, 'distance_um'],
        df_5.loc[high_mask, 'source_intensity'],
        s=14, color='#d62728',
    )
    plt.xlabel(f'Self-channel {ch} NN distance (µm)')
    plt.ylabel(f'Channel {ch} intensity (a.u.)')
    plt.title(f'Self {ch} vs {ch}: d ≤ 5 µm — intensity ≥ {thresh}')
    plt.xlim(0, 5)
    plt.ylim(0, max(6000, thresh * 2))
    n_high = high_mask.sum()
    plt.text(
        0.05, 0.95, f'n(≥{thresh}) = {n_high}',
        transform=plt.gca().transAxes, fontsize=10, va='top',
        bbox=dict(facecolor='white', alpha=0.7, edgecolor='none'),
    )
    plt.savefig(f'SelfNN_ch{ch}_int_ge{thresh}_dle5um.pdf', format='pdf')
    plt.savefig(f'SelfNN_ch{ch}_int_ge{thresh}_dle5um.eps', format='eps')
    plt.show()

# ============================================================
# G) Subset analysis (self-channel version)
#    Same size/intensity filters, self-channel distances only
#    -> SelfChannel_3ChannelSubset.csv
# ============================================================

sub1 = [obj for obj in l1 if obj.majorSize < 0.4 and obj.punctumIntensity < 2500]
sub3 = [obj for obj in l3 if obj.majorSize < 0.4 and obj.punctumIntensity < 10000]
sub4 = [obj for obj in l4 if obj.majorSize < 0.4 and obj.punctumIntensity < 8000]

self_sub_dict = {}

for ch_label, ch_sub in [('self_1', sub1), ('self_3', sub3), ('self_4', sub4)]:
    dists = []
    for p in ch_sub:
        if 'dist' not in p.characteristics:
            continue
        if p.channel not in p.characteristics['dist']:
            continue
        dists.append(p.characteristics['dist'][p.channel][0])
    self_sub_dict[ch_label] = dists

# Pad to equal length
temp_sub = [len(v) for v in self_sub_dict.values()]
max_sub = max(temp_sub) if temp_sub else 0
for k in self_sub_dict:
    self_sub_dict[k] = list(self_sub_dict[k]) + [None] * (max_sub - len(self_sub_dict[k]))

df_self_sub = pd.DataFrame(self_sub_dict)
df_self_sub.to_csv('SelfChannel_3ChannelSubset.csv', index=False)
print("Saved SelfChannel_3ChannelSubset.csv")

# ============================================================
# Size vs Intensity plots per channel (unchanged from original)
# ============================================================

for ch_list, ch_num in [(l1, 1), (l3, 3), (l4, 4)]:
    if not ch_list:
        continue
    plt.figure()
    plt.title(f'Size vs Intensity at channel {ch_num}')
    plt.scatter(
        [obj.punctumIntensity for obj in ch_list],
        [obj.majorSize for obj in ch_list],
    )
    plt.ylabel('Major Axis Size, microns')
    plt.xlabel('Grayscale intensity')
    plt.ylim((0, 1.2))
    plt.savefig(f'SelfNN_Size_vs_Intensity_channel_{ch_num}.pdf', format='pdf')
    plt.savefig(f'SelfNN_Size_vs_Intensity_channel_{ch_num}.eps', format='eps')
    plt.show()

print("\n=== Self-channel NN analysis complete ===")