"""
Self-Channel Nearest-Neighbor Distance Plotting
=================================================
Mirrors the cross-channel plotting script for self-channel (same-channel)
nearest-neighbor distances.

Input CSV: SelfChannel_3ChannelImages_upto5um.csv
  Columns: self_1, self_3, self_4
  
Code was generated by Claude and "the relevant parts were" verified by STP
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit
import matplotlib.colors as mcolors

plt.rcParams['pdf.fonttype'] = 42
scaleparameter = 1000
gauss = 0

# ============================================================
# 0) Load self-channel distance data
# ============================================================

df = pd.read_csv(r'SelfChannel_3ChannelImages_upto5um.csv')
distDict = df.to_dict()

# Strip NaNs from each column
for key in distDict.keys():
    index = (np.isnan([distDict[key][dist] for dist in distDict[key].keys()]) == False)
    distDict[key] = list(np.array([distDict[key][dist] for dist in distDict[key].keys()])[index]*scaleparameter)

# ============================================================
# Helper functions (same as cross-channel script)
# ============================================================

def plot_loghist(x, bins, plot):
    hist, bins = np.histogram(x, bins=bins, range=(0.001*scaleparameter, 10*scaleparameter))
    logbins = np.logspace(np.log10(bins[0]), np.log10(bins[-1]), len(bins))
    n, hist2, bins2 = plot.hist(x, bins=logbins, alpha=1.0)
    plot.set_xscale('log')
    return n, logbins

def loghist(x, binarray, plot):
    logbins = np.logspace(np.log10(binarray[0]), np.log10(binarray[-1]), len(binarray))
    n, hist2, bins2 = plot.hist(x, bins=logbins, alpha=1.0, range=(0.01*scaleparameter, 10*scaleparameter))
    plot.set_xscale('log')
    return n, hist2, bins2, logbins

def gauss(x, mu, sigma, A):
    return (A**2) * np.exp(-(x - mu)**2 / (2 * sigma**2))

def logbimodal(x, mu1, s1, A1, mu2, s2, A2):
    return gauss(x, mu1, s1, A1) + gauss(x, mu2, s2, A2)

def lighten_color(color, amount=1.4):
    try:
        c = mcolors.cnames[color]
    except KeyError:
        c = color
    c = mcolors.to_rgb(c)
    return tuple(1 - (1 - comp) / amount for comp in c)

def darken_color(color, amount=0.8):
    try:
        c = mcolors.cnames[color]
    except KeyError:
        c = color
    c = mcolors.to_rgb(c)
    return tuple(comp * amount for comp in c)

def get_corrs_self(distDict):
    """
    Compute pairwise correlations between all self-channel distance
    columns (self_1 vs self_3, self_1 vs self_4, self_3 vs self_4).
    """
    keys = list(distDict.keys())
    corr_dict = {}

    for i in range(len(keys)):
        for j in range(i + 1, len(keys)):
            a = np.array(distDict[keys[i]], dtype=float)
            b = np.array(distDict[keys[j]], dtype=float)

            n = min(len(a), len(b))
            a = a[:n]
            b = b[:n]

            mask = ~np.isnan(a) & ~np.isnan(b)
            a = a[mask]
            b = b[mask]

            if len(a) < 3:
                continue

            rho = np.corrcoef(a, b)[0, 1]
            pair_label = f'{keys[i]} vs {keys[j]}'
            corr_dict[pair_label] = [rho, len(a)]

    return corr_dict

def corr_CI(corrs, ns):
    upper = []
    lower = []
    for i in range(len(corrs)):
        zr = 0.5 * np.log((1 + corrs[i]) / (1 - corrs[i]))
        ur = zr + 1.96 * np.sqrt(1 / (ns[i] - 3))
        lr = zr - 1.96 * np.sqrt(1 / (ns[i] - 3))
        upper.append(np.tanh(ur) - corrs[i])
        lower.append(corrs[i] - np.tanh(lr))
    return [upper, lower]

# ============================================================
# Color and label maps for self-channel
# ============================================================

color_map = {
    'self_1': '#e800cc',   # dark magenta  (mtRNA)
    'self_3': '#23D5D5',   # cyan          (MRG)
    'self_4': '#FFDE21',   # yellow        (mtDNA)
}

label_map = {
    'self_1': '$d_{mtRNA,mtRNA}$',
    'self_3': '$d_{MRG,MRG}$',
    'self_4': '$d_{mtDNA,mtDNA}$',
}

label_map_plain = {
    'self_1': 'd_{mtRNA,mtRNA}',
    'self_3': 'd_{MRG,MRG}',
    'self_4': 'd_{mtDNA,mtDNA}',
}

# ============================================================
# 1) Count distributions (one subplot per self-channel)
# ============================================================

n_keys = len(distDict.keys())
fig, ax = plt.subplots(1, n_keys, figsize=(n_keys * 4 + 2, 4))
fig.suptitle('Self-Channel NN Count Distributions', fontsize=20)

if n_keys == 1:
    ax = [ax]

c = 0
for key in distDict.keys():
    curve_color = color_map.get(key, '#888888')
    bar_color = lighten_color(curve_color, amount=1.8)

    hist, bins = plot_loghist(distDict[key], 35, ax[c])

    for patch in ax[c].patches:
        patch.set_facecolor(bar_color)
        patch.set_edgecolor('black')
        patch.set_linewidth(0.8)

    b1 = bins[1:]
    b2 = bins[:-1]
    x_pmf = (b1 + b2) / 2

    ax[c].set_xscale('log')
    if scaleparameter == 1: 
        ax[c].set_xlabel('Distance (µm)', fontsize=18)
    elif scaleparameter == 1000:
        ax[c].set_xlabel('Distance (nm)', fontsize=18)
    else:
        ax[c].set_xlabel('Distance (µm/{})'.format(scaleparameter), fontsize=18)
    ax[c].set_ylabel('Count', fontsize=18)
    ax[c].tick_params(axis='both', labelsize=16)
    ax[c].set_ylim((0, 500))
    ax[c].set_xlim((0.005*scaleparameter, 25*scaleparameter))
    ax[c].set_box_aspect(4 / 5)
    ax[c].set_title(label_map[key], fontsize=20, pad=10)

    try:
        if gauss == 1:
            g1_data = [dist for dist in distDict[key] if dist <  0.2*scaleparameter]
            g2_data = [dist for dist in distDict[key] if dist >= 0.2*scaleparameter]
            m1 = np.mean(g1_data)
            s1 = np.std(g1_data)
            m2 = np.mean(g2_data)
            s2 = np.std(g2_data)
            a1 = hist[:12].max()/len(distDict[key])
            a2 = hist[12:].max()/len(distDict[key])
            param, cov = curve_fit(logbimodal, np.log(x_pmf), hist, maxfev=10000, p0=[m1,s1,a1,m2,s2,a1])
            x_ = np.linspace(-7+np.log10(scaleparameter), 10+np.log10(scaleparameter), 1000)
            ax[c].plot(np.exp(x_), logbimodal(x_, *param), color='black', linewidth=1.5)
            ax[c].plot(np.exp(x_), gauss(x_, *param[3:]), '--',
                       color=lighten_color(curve_color, 1.4), linewidth=1.2)
            ax[c].plot(np.exp(x_), gauss(x_, *param[:3]), '--',
                       color=darken_color(curve_color, 0.6), linewidth=1.2)
            ax[c].legend(['Combined fit', 'Log-normal fit 1', 'Log-normal fit 2'],
                         fontsize=16, frameon=False, loc='best')
        else:
            g_data = distDict[key]
            m = np.mean(g_data)
            s = np.std(g_data)
            a = hist.max()/len(distDict[key])
            param, cov = curve_fit(gauss, np.log(x_pmf), hist, maxfev=10000, p0=[m,s,a])
            x_ = np.linspace(-7+np.log10(scaleparameter), 10+np.log10(scaleparameter), 1000)
            ax[c].plot(np.exp(x_), gauss(x_, *param), color='black', linewidth=1.5)
            ax[c].legend(['Log-normal fit'], fontsize=16, frameon=False, loc='best')
    except RuntimeError:
        pass

    c += 1

fig.tight_layout()
fig.savefig('self-channel-count-distributions.eps', dpi=300)
fig.savefig('self-channel-count-distributions.pdf', dpi=300)
plt.show()

# ============================================================
# 2) Probability density distributions
# ============================================================

# Compute number of rows/cols for subplot grid (3 columns)
n_keys = len(distDict.keys())
n_cols = 3
n_rows = int(np.ceil(n_keys / n_cols))

fig1, ax1 = plt.subplots(n_rows, n_cols, figsize=(20, n_rows * 4.6))
fig1.suptitle('Self-Channel NN Probability Density', fontsize=20)

# Handle single-row case
if n_rows == 1:
    ax1 = ax1.reshape(1, -1)

c = 0
# We need bins from the first plot_loghist call for loghist
_, ref_bins = np.histogram(list(distDict.values())[0], bins=35, range=(0.001*scaleparameter, 10*scaleparameter))

for key in distDict.keys():
    row = c // n_cols
    col = c % n_cols

    key2 = label_map.get(key, key)
    curve_color = color_map.get(key, '#888888')
    bar_color = lighten_color(curve_color, 1.8)

    ax = ax1[row, col]
    ax.set_title(key2, fontsize=22, pad=10)

    hist, bins2, rects, logbins = loghist(distDict[key], ref_bins, ax)

    for r in rects:
        r.set_facecolor(bar_color)
        r.set_edgecolor('black')
        r.set_linewidth(0.8)
        r.set_height(r.get_height() / len(distDict[key]))
        r.set_zorder(2)
        r.set_label('_nolegend_')

    b1 = logbins[1:]
    b2 = logbins[:-1]
    x_pmf = (b1 + b2) / 2
    x_ = np.linspace(-7+np.log10(scaleparameter), 10+np.log10(scaleparameter), 1000)

    ax.set_xscale('log')
    if scaleparameter == 1: 
        ax.set_xlabel('Distance (µm)', fontsize=18)
    elif scaleparameter == 1000:
        ax.set_xlabel('Distance (nm)', fontsize=18)
    else:
        ax.set_xlabel('Distance (µm/{})'.format(scaleparameter), fontsize=18)
    ax.set_ylabel('Probability Density', fontsize=18)
    ax.yaxis.labelpad = 0.5
    ax.tick_params(axis='both', labelsize=18, pad=0)
    ax.set_ylim(0, 0.5)
    ax.set_xlim((0.01*scaleparameter, 10*scaleparameter))
    ax.set_box_aspect(3 / 5)

    # Gray shaded bands (same as cross-channel)
    ax.axvspan(0.01*scaleparameter, 0.1*scaleparameter, facecolor='#bdbdbd', alpha=1.0, zorder=0, label='_nolegend_')
    ax.axvspan(0.1*scaleparameter,  0.2*scaleparameter, facecolor='#d9d9d9', alpha=1.0, zorder=0, label='_nolegend_')
    ax.axvspan(0.2*scaleparameter,  10*scaleparameter,  facecolor='#eeeeee', alpha=1.0, zorder=0, label='_nolegend_')

    # Counts inside each shaded band
    data = np.asarray(distDict[key])
    ranges = [(0.01*scaleparameter, 0.1*scaleparameter), (0.1*scaleparameter, 0.2*scaleparameter), (0.2*scaleparameter, 10*scaleparameter)]
    y_frac = 0.65

    for rmin, rmax in ranges:
        count = ((data >= rmin) & (data < rmax)).sum()
        xpos = (rmin * rmax) ** 0.5
        ax.text(xpos, y_frac, f"n={count}",
                ha='center', va='center', fontsize=14, color='black',
                transform=ax.get_xaxis_transform(), zorder=4)

    # Curve fitting
    try:
        if gauss == 1:
            g1_data = [dist for dist in distDict[key] if dist <  0.2*scaleparameter]
            g2_data = [dist for dist in distDict[key] if dist >= 0.2*scaleparameter]
            m1 = np.mean(g1_data)
            s1 = np.std(g1_data)
            m2 = np.mean(g2_data)
            s2 = np.std(g2_data)
            a1 = hist[:12].max()/len(distDict[key])
            a2 = hist[12:].max()/len(distDict[key])
            param, cov = curve_fit(logbimodal, np.log(x_pmf),
                                   hist / len(distDict[key]),
                                   maxfev=10000, p0=[m1, s1, a1, m2, s2, a2])
            ax.plot(np.exp(x_), logbimodal(x_, *param),
                    color='black', linewidth=1.5, zorder=3, label='Combined fit')
            leg = ax.legend(loc='upper right', fontsize=16, frameon=False,
                            bbox_to_anchor=(1.0, 1.00))
            leg.set_zorder(10)
        else:
            g_data = distDict[key]
            m = np.mean(g_data)
            s = np.std(g_data)
            a = hist.max()/len(distDict[key])
            param, cov = curve_fit(gauss, np.log(x_pmf),
                                   hist / len(distDict[key]),
                                   maxfev=10000, p0=[m, s, a])
            ax.plot(np.exp(x_), gauss(x_, *param),
                    color='black', linewidth=1.5, zorder=3, label='Log-normal fit')
            leg = ax.legend(loc='upper right', fontsize=16, frameon=False)
            leg.set_zorder(10)
    except RuntimeError:
        pass

    c += 1

# Remove extra empty subplots
total_axes = ax1.flatten()
for i in range(c, len(total_axes)):
    fig1.delaxes(total_axes[i])

fig1.tight_layout(pad=0.6, w_pad=0.4, h_pad=0.8)
fig1.subplots_adjust(wspace=0.18, hspace=0.25)
fig1.savefig('self-channel-probability-density.eps', dpi=300)
fig1.savefig('self-channel-probability-density.pdf', dpi=300)
plt.show()

# ============================================================
# 3) Pairwise correlations between self-channel distances
# ============================================================

corr_dict = get_corrs_self(distDict)

if corr_dict:
    corrs = []
    ns = []
    pair_labels = []

    # Pretty-print pair labels
    channel_name = {'self_1': 'mtRNA', 'self_3': 'MRG', 'self_4': 'mtDNA'}

    for key in corr_dict.keys():
        corrs.append(corr_dict[key][0])
        ns.append(corr_dict[key][1])
        # Convert e.g. "self_1 vs self_3" -> "mtRNA vs MRG"
        parts = key.split(' vs ')
        pretty = f"{channel_name.get(parts[0].strip(), parts[0])} vs {channel_name.get(parts[1].strip(), parts[1])}"
        pair_labels.append(pretty)

    CIs = corr_CI(corrs, ns)

    print(f"Self-channel correlation values: {corrs}")
    print(f"Self-channel confidence intervals: {CIs}")

    fig2, ax2 = plt.subplots(figsize=(6, 5))

    # Color bars by the first channel in each pair
    bar_colors = []
    for key in corr_dict.keys():
        first_key = key.split(' vs ')[0].strip()
        bar_colors.append(lighten_color(color_map.get(first_key, '#888888'), 1.4))

    ax2.bar(pair_labels, corrs, yerr=CIs, alpha=0.7,
            color=bar_colors, edgecolor='black', linewidth=0.8,
            capsize=10, zorder=1)
    ax2.set_ylabel('Correlation Coefficient (ρ)', fontsize=12)
    ax2.set_xlabel('Self-Channel Pairs', fontsize=12)
    ax2.set_ylim((-1, 1))
    ax2.tick_params(axis='both', labelsize=10)
    ax2.set_title('Correlation of Self-Channel Distributions', fontsize=14)
    ax2.set_box_aspect(5 / 4.5)

    # Rotate x-labels if needed
    plt.setp(ax2.get_xticklabels(), rotation=15, ha='right')

    fig2.tight_layout()
    fig2.savefig('self-channel-correlation-barplot.eps', dpi=300)
    fig2.savefig('self-channel-correlation-barplot.pdf', dpi=300)
    plt.show()
else:
    print("Not enough self-channel columns for pairwise correlation.")

print("\n=== Self-channel plotting complete ===")